DOC: Remove the ToDo list from the `README` file
Remove the ToDo list from the `README` file: an issue has been opened
with the removed contents so that a record is kept/progress can be
monitored:
https://github.com/InsightSoftwareConsortium/ITKTrimmedPointSetRegistration/issues/4

Fixes:
```
Checking
dist/itk_trimmedpointsetregistration-1.0.0-cp38-cp38-manylinux_2_28_x86_64.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be
         rendered on PyPI.
         line 50: Warning: Bullet list ends without a blank line; unexpected
         unindent.
Error: Process completed with exit code 1.
```

raised for example at:
https://github.com/InsightSoftwareConsortium/ITKTrimmedPointSetRegistration/actions/runs/9749081368/job/26905489586#step:7:137

which effectively prevents from building the module's Python package.